# Generated by Django 6.0.6 on 2026-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('placement_percentage', models.IntegerField()),
                ('official_website', models.URLField()),
                ('courses', models.TextField()),
            ],
        ),
    ]
