# Generated by Django 6.0.6 on 2026-06-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('registration_last_date', models.DateField()),
                ('official_website', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
