# Generated by Django 6.0.6 on 2026-06-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pre-Primary Schools', 'Pre-Primary Schools'), ('Primary to Higher Secondary', 'Primary to Higher Secondary'), ('Colleges', 'Colleges')], max_length=100)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
