# Generated by Django 4.2.11 on 2026-06-15 11:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_counsellinglead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('general', 'General'), ('sc_st', 'SC/ST'), ('obc', 'OBC'), ('minority', 'Minority'), ('girl_child', 'Girl Child'), ('disability', 'Disability'), ('merit_based', 'Merit-Based')], max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('min_income', models.IntegerField()),
                ('max_income', models.IntegerField()),
                ('min_percentage', models.FloatField(default=0)),
                ('application_deadline', models.DateField()),
                ('required_documents', models.TextField()),
                ('application_steps', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='distance_km',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='highest_package',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='hostel_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='hostel_fees',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='college',
            name='student_reviews',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='counsellinglead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedcollege',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_interest', models.CharField(blank=True, max_length=100)),
                ('career_goal', models.CharField(blank=True, max_length=255)),
                ('academic_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrance_exam_score', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('budget', models.IntegerField(blank=True, default=0)),
                ('stream', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('documents_submitted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'is_parent': False}, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('registered', 'Registered'), ('completed', 'Completed')], default='recommended', max_length=20)),
                ('ai_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('profile', 'Complete Profile'), ('scholarship', 'Apply for Scholarship'), ('exam_prep', 'Prepare for Entrance Exam'), ('college_compare', 'Compare Colleges'), ('counsellor', 'Contact Counsellor'), ('application', 'Submit Application')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CollegeComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colleges', models.ManyToManyField(to='accounts.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('admission_confirmed', 'Admission Confirmed')], default='submitted', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_colleges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_session_id', models.CharField(max_length=100, unique=True)),
                ('messages', models.JSONField(default=list)),
                ('career_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('exam', 'Exam Registration'), ('application', 'Application Deadline'), ('admission', 'Admission Registration'), ('counselling', 'Counselling Date')], max_length=50)),
                ('deadline_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_deadlines', to='accounts.college')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_deadlines', to='accounts.exam')),
            ],
        ),
    ]
